name: Generate PageSpeed Metrics

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  pagespeed:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Generate PageSpeed metrics
        uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.pagespeed.svg
          token: ${{ secrets.GITHUB_TOKEN }}
          base: ""
          plugin_pagespeed: yes
          plugin_pagespeed_url: https://thierryswebsite.netlify.app/
          plugin_pagespeed_token: ${{ secrets.PAGESPEED_TOKEN }}
          # --- KONFIGURASI WARNA DI SINI ---
          config_colorscheme: light
          config_custom_colors: >-
            text:#002B5B,
            title:#002B5B,
            icon:#002B5B,
            score:#002B5B
